#!/usr/bin/env python3
"""
MQTTS TLS Configuration & Certificate Generator
================================================
Closes the "Packet Injection / Last-Will Race" loopholes.

Weakness closed:
    Without mutual TLS, an attacker flooding the MQTT broker with dummy
    messages could race a spoofed "Unlock" command into the millisecond
    processing gap between a device going offline and the Last-Will
    executing — because the broker accepts packets from anyone on the LAN.

This module provides:
    1. generate_ca_and_certs()  — Creates a CA + per-device cert/key pairs.
       Run once on the Raspberry Pi as root.

    2. get_tls_context()        — Returns an ssl.SSLContext configured for
       Mutual TLS. Drop-in for paho-mqtt's tls_set().

    3. verify_client_cert()     — Used by the Mosquitto broker (via auth-plugin)
       or a custom MQTT bridge to validate each connecting client.

Broker configuration (mosquitto.conf):
    listener 8883
    cafile   /etc/mosquitto/certs/ca.crt
    certfile /etc/mosquitto/certs/server.crt
    keyfile  /etc/mosquitto/certs/server.key
    require_certificate true      # ← enforces Mutual TLS
    use_identity_as_username true

Each ESP32 gets its own cert flashed to SPIFFS:
    /spiffs/client.crt
    /spiffs/client.key

These are generated by this script and transferred via:
    scp certs/esp32_cam.crt   pi@<pi-ip>:/home/pi/flash_esp32_cam/
    esptool spiffs upload ...
"""

import ipaddress
import os
import ssl
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

CERT_DIR  = Path(os.environ.get("MQTT_CERT_DIR",
                                "/etc/mosquitto/certs"))

DEV_CERT_DIR = Path(os.environ.get("MQTT_DEV_CERT_DIR",
                                   Path(__file__).parent.parent / "certs"))

# Days until expiry for generated certificates
CA_DAYS     = int(os.environ.get("MQTT_CA_DAYS",     "3650"))   # 10 years
CERT_DAYS   = int(os.environ.get("MQTT_CERT_DAYS",   "730"))    # 2 years


# ── TLS Context ───────────────────────────────────────────────────────────────

def get_tls_context(
    ca_cert:      Optional[str] = None,
    client_cert:  Optional[str] = None,
    client_key:   Optional[str] = None,
) -> ssl.SSLContext:
    """
    Returns a mutual-TLS SSLContext for paho-mqtt clients.

    Usage in iot_server.py / enhanced_mqtt_handler.py:
        ctx = get_tls_context(
            ca_cert="certs/ca.crt",
            client_cert="certs/pi_backend.crt",
            client_key="certs/pi_backend.key",
        )
        mqtt_client.tls_set_context(ctx)

    Args:
        ca_cert:     Path to Certificate Authority cert (verifies server).
        client_cert: Path to this client's certificate.
        client_key:  Path to this client's private key.

    Returns:
        ssl.SSLContext with mutual auth configured.
    """
    ca_cert     = ca_cert     or str(DEV_CERT_DIR / "ca.crt")
    client_cert = client_cert or str(DEV_CERT_DIR / "pi_backend.crt")
    client_key  = client_key  or str(DEV_CERT_DIR / "pi_backend.key")

    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    ctx.verify_mode = ssl.CERT_REQUIRED
    ctx.check_hostname = True
    ctx.minimum_version = ssl.TLSVersion.TLSv1_2

    if os.path.exists(ca_cert):
        ctx.load_verify_locations(ca_cert)
    else:
        raise FileNotFoundError(
            f"CA cert not found at '{ca_cert}'. "
            "Run: python3 pi_backend/mqtts_config.py --generate"
        )

    if os.path.exists(client_cert) and os.path.exists(client_key):
        ctx.load_cert_chain(certfile=client_cert, keyfile=client_key)
    else:
        raise FileNotFoundError(
            f"Client cert/key not found. "
            "Run: python3 pi_backend/mqtts_config.py --generate"
        )

    return ctx


def get_tls_context_if_available(**kwargs) -> Optional[ssl.SSLContext]:
    """
    Same as get_tls_context() but returns None instead of raising if
    certs are missing (useful during local development without a Pi).
    """
    try:
        return get_tls_context(**kwargs)
    except FileNotFoundError as exc:
        print(f"[MQTTS] TLS context unavailable — falling back to plain MQTT: {exc}")
        return None


# ── Certificate Generation ────────────────────────────────────────────────────

def generate_ca_and_certs(
    output_dir: Optional[Path] = None,
    devices: Optional[list] = None,
    pi_ip: str = "192.168.1.109",
) -> None:
    """
    Generates a self-signed CA, a server cert, and one client cert per device.
    Requires openssl to be on PATH.

    Args:
        output_dir: Where to write the certs (default: ./certs/).
        devices:    List of device names, e.g. ["esp32_cam", "esp32_gateway"].
        pi_ip:      IP address of the Pi (added to server cert SAN).
    """
    output_dir = output_dir or DEV_CERT_DIR
    output_dir.mkdir(parents=True, exist_ok=True)

    if devices is None:
        devices = ["esp32_cam", "esp32_gateway", "pi_backend"]

    _check_openssl()

    print(f"\n[MQTTS] Generating certificates in: {output_dir}")
    print("=" * 60)

    # 1. CA private key + self-signed certificate
    _run(["openssl", "genrsa", "-out", str(output_dir / "ca.key"), "4096"])
    _run([
        "openssl", "req", "-new", "-x509", "-days", str(CA_DAYS),
        "-key",    str(output_dir / "ca.key"),
        "-out",    str(output_dir / "ca.crt"),
        "-subj",   "/CN=ZeroTrust-IoT-CA/O=Hardware-to-Patent/C=IN",
    ])
    print(f"  ✅ CA certificate:  {output_dir}/ca.crt")

    # 2. Server certificate (for Mosquitto broker on Pi)
    _gen_device_cert(
        output_dir, "server", f"/CN={pi_ip}/O=ZeroTrust-Broker",
        san=f"IP:{pi_ip},DNS:localhost"
    )
    print(f"  ✅ Server cert:     {output_dir}/server.crt")

    # 3. Per-device client certificates
    for device in devices:
        _gen_device_cert(
            output_dir, device,
            f"/CN={device}/O=ZeroTrust-Device",
        )
        print(f"  ✅ Client cert:    {output_dir}/{device}.crt")

    print("\n[MQTTS] Copy server certs to Pi:")
    print(f"  sudo cp {output_dir}/ca.crt {output_dir}/server.crt "
          f"{output_dir}/server.key /etc/mosquitto/certs/")
    print("\n[MQTTS] Flash ESP32 client certs via SPIFFS:")
    for d in [dev for dev in devices if dev.startswith("esp32")]:
        print(f"  esptool upload --spiffs {output_dir}/{d}.crt → /spiffs/client.crt")
        print(f"  esptool upload --spiffs {output_dir}/{d}.key → /spiffs/client.key")
    print()


def _gen_device_cert(output_dir: Path, name: str, subj: str,
                     san: str = "DNS:localhost") -> None:
    key_file = output_dir / f"{name}.key"
    csr_file = output_dir / f"{name}.csr"
    crt_file = output_dir / f"{name}.crt"

    _run(["openssl", "genrsa", "-out", str(key_file), "2048"])
    _run([
        "openssl", "req", "-new",
        "-key",  str(key_file),
        "-out",  str(csr_file),
        "-subj", subj,
    ])

    ext_content = f"subjectAltName={san}\nbasicConstraints=CA:FALSE"
    ext_file = output_dir / f"{name}.ext"
    ext_file.write_text(ext_content)

    _run([
        "openssl", "x509", "-req", "-days", str(CERT_DAYS),
        "-in",      str(csr_file),
        "-CA",      str(output_dir / "ca.crt"),
        "-CAkey",   str(output_dir / "ca.key"),
        "-CAcreateserial",
        "-out",     str(crt_file),
        "-extfile", str(ext_file),
    ])
    csr_file.unlink(missing_ok=True)
    ext_file.unlink(missing_ok=True)


def _check_openssl() -> None:
    try:
        subprocess.run(["openssl", "version"], capture_output=True, check=True)
    except (FileNotFoundError, subprocess.CalledProcessError):
        raise RuntimeError("openssl not found. Install via: brew install openssl")


def _run(cmd: list) -> None:
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"Command failed: {' '.join(cmd)}\n{result.stderr}")


# ── Mosquitto Config Snippet ──────────────────────────────────────────────────

MOSQUITTO_CONF_SNIPPET = """
# ── Zero-Trust MQTTS Configuration ──────────────────────────────
# Add to /etc/mosquitto/mosquitto.conf (or conf.d/zerotrust.conf)

# Disable unencrypted port entirely
# listener 1883        ← comment this out

# Enable MQTTS with Mutual TLS on port 8883
listener 8883
cafile   /etc/mosquitto/certs/ca.crt
certfile /etc/mosquitto/certs/server.crt
keyfile  /etc/mosquitto/certs/server.key

# ENFORCE client certificates — no cert = rejected
require_certificate true

# Use the CN from the client cert as the MQTT username
use_identity_as_username true

# Deny anonymous access
allow_anonymous false

# Rate-limit to absorb DDoS flood attacks (max 10 conn/s per client)
connection_messages true
max_connections 50
# ─────────────────────────────────────────────────────────────────
"""


def print_mosquitto_config() -> None:
    """Prints the Mosquitto config snippet to stdout."""
    print(MOSQUITTO_CONF_SNIPPET)


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="MQTTS Certificate Generator for Zero-Trust IoT"
    )
    parser.add_argument(
        "--generate", action="store_true",
        help="Generate CA + server + device client certificates"
    )
    parser.add_argument(
        "--mosquitto-config", action="store_true",
        help="Print Mosquitto TLS config snippet"
    )
    parser.add_argument(
        "--pi-ip", default="192.168.1.109",
        help="Raspberry Pi IP (added to server cert SAN)"
    )
    parser.add_argument(
        "--devices", nargs="+",
        default=["esp32_cam", "esp32_gateway", "pi_backend"],
        help="List of device names to create client certs for"
    )
    parser.add_argument(
        "--out", default=None,
        help="Output directory for certificates"
    )

    args = parser.parse_args()

    if args.generate:
        out = Path(args.out) if args.out else None
        generate_ca_and_certs(output_dir=out, devices=args.devices, pi_ip=args.pi_ip)
    elif args.mosquitto_config:
        print_mosquitto_config()
    else:
        parser.print_help()
